   FROM node:16.18-alpine

 # Create App Directory
    RUN mkdir -p /usr/src/app
    WORKDIR /usr/src/app
    
    # Install Dependencies
    COPY package*.json ./
    
    RUN npm install --silent
    
    # Copy app source code
    COPY . .
    
    # Exports
    EXPOSE 9000
    
    CMD ["npm","start"]

# node block

# FROM node:alpine3.16 as nodework

# WORKDIR /msgapi

# COPY package.json .

# RUN npm install

# COPY . .

# RUN node server.js






# #nginx block

# FROM nginx:1.23-alpine

# WORKDIR /usr/share/nginx/html

# RUN rm -rf ./*

# COPY --from=nodework /myapp/build .

# ENTRYPOINT ["nginx", "-g", "daemon off;"]